import { and, asc, eq } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { insuranceItems } from "@/db/maintenance-operations-schema";
import { assets, homes, rooms } from "@/db/schema";
import {
    requireHomeAccess,
    requireRoomInHome,
} from "@/src/server/authorization";
import { errorResponse, requestId } from "@/src/server/http";
import { createTextPdf } from "@/src/server/pdf/simple-pdf";

export async function GET(request: Request) {
    const id = requestId(request);
    try {
        const input = z
            .object({
                homeId: z.string().uuid(),
                roomId: z.string().uuid().optional(),
            })
            .parse(
                Object.fromEntries(new URL(request.url).searchParams.entries()),
            );
        await requireHomeAccess(input.homeId);
        if (input.roomId) await requireRoomInHome(input.roomId, input.homeId);

        const [home] = await db
            .select({ name: homes.name })
            .from(homes)
            .where(eq(homes.id, input.homeId))
            .limit(1);
        const rows = await db
            .select({
                name: insuranceItems.name,
                category: insuranceItems.category,
                quantity: insuranceItems.quantity,
                unitValue: insuranceItems.unitValue,
                currency: insuranceItems.currency,
                purchaseDate: insuranceItems.purchaseDate,
                notes: insuranceItems.notes,
                roomName: rooms.name,
                assetName: assets.name,
            })
            .from(insuranceItems)
            .leftJoin(rooms, eq(rooms.id, insuranceItems.roomId))
            .leftJoin(assets, eq(assets.id, insuranceItems.assetId))
            .where(
                input.roomId
                    ? and(
                          eq(insuranceItems.homeId, input.homeId),
                          eq(insuranceItems.roomId, input.roomId),
                      )
                    : eq(insuranceItems.homeId, input.homeId),
            )
            .orderBy(asc(insuranceItems.category), asc(insuranceItems.name));

        const totals = new Map<string, number>();
        const lines = rows.map((item, index) => {
            const total = Number(item.unitValue) * item.quantity;
            totals.set(item.currency, (totals.get(item.currency) ?? 0) + total);
            return [
                `${index + 1}. ${item.name} [${item.category}]`,
                `Qty ${item.quantity} x ${Number(item.unitValue).toFixed(2)} ${item.currency} = ${total.toFixed(2)} ${item.currency}`,
                item.roomName ? `Room: ${item.roomName}` : "Room: whole home",
                item.assetName ? `Linked asset: ${item.assetName}` : "",
                item.purchaseDate ? `Purchased: ${item.purchaseDate}` : "",
                item.notes ? `Notes: ${item.notes}` : "",
                "",
            ]
                .filter(Boolean)
                .join(" | ");
        });
        lines.push("", "TOTALS");
        for (const [currency, total] of totals) {
            lines.push(`${currency}: ${total.toFixed(2)}`);
        }
        lines.push(
            "",
            `Generated by Homi on ${new Date().toISOString().slice(0, 10)}`,
        );

        const title = `${home?.name ?? "Home"} - insurance inventory`;
        const pdf = createTextPdf(title, lines);
        const filename = `${(home?.name ?? "homi")
            .toLowerCase()
            .replace(/[^a-z0-9]+/gu, "-")}-insurance-inventory.pdf`;
        return new Response(new Uint8Array(pdf), {
            headers: {
                "content-type": "application/pdf",
                "content-disposition": `attachment; filename="${filename}"`,
                "cache-control": "private, no-store",
            },
        });
    } catch (error) {
        return errorResponse(error, id);
    }
}
