import {
    boolean,
    date,
    index,
    integer,
    jsonb,
    numeric,
    pgEnum,
    pgTable,
    text,
    timestamp,
    uniqueIndex,
    uuid,
} from "drizzle-orm/pg-core";

const timestamps = {
    createdAt: timestamp("created_at", { withTimezone: true })
        .defaultNow()
        .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
        .defaultNow()
        .notNull(),
};

export const homeRole = pgEnum("home_role", [
    "OWNER",
    "ADMIN",
    "MEMBER",
    "VIEWER",
]);
export const assetStatus = pgEnum("asset_status", [
    "ACTIVE",
    "NEEDS_ATTENTION",
    "UNDER_REPAIR",
    "REPLACED",
    "ARCHIVED",
]);
export const frequencyType = pgEnum("frequency_type", [
    "ONCE",
    "DAILY",
    "WEEKLY",
    "MONTHLY",
    "YEARLY",
    "CUSTOM",
]);
export const priority = pgEnum("priority", [
    "LOW",
    "MEDIUM",
    "HIGH",
    "CRITICAL",
]);
export const documentType = pgEnum("document_type", [
    "INVOICE",
    "WARRANTY",
    "MANUAL",
    "CERTIFICATE",
    "CONTRACT",
    "PHOTO",
    "OTHER",
]);
export const repairStatus = pgEnum("repair_status", [
    "OPEN",
    "SCHEDULED",
    "IN_PROGRESS",
    "COMPLETED",
    "CANCELLED",
]);
export const storageProvider = pgEnum("storage_provider", ["LOCAL", "S3"]);
export const reminderChannel = pgEnum("reminder_channel", ["IN_APP", "EMAIL"]);
export const deliveryStatus = pgEnum("delivery_status", [
    "PENDING",
    "DELIVERED",
    "FAILED",
    "SKIPPED",
]);

// Better Auth tables. UUIDs are generated by PostgreSQL and remain opaque to clients.
export const user = pgTable(
    "user",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        name: text("name").notNull(),
        email: text("email").notNull(),
        emailVerified: boolean("email_verified").default(false).notNull(),
        image: text("image"),
        onboardingStep: integer("onboarding_step").default(0).notNull(),
        onboardingCompletedAt: timestamp("onboarding_completed_at", {
            withTimezone: true,
        }),
        ...timestamps,
    },
    (table) => [uniqueIndex("user_email_unique").on(table.email)],
);

export const session = pgTable(
    "session",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        token: text("token").notNull(),
        ipAddress: text("ip_address"),
        userAgent: text("user_agent"),
        userId: uuid("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        ...timestamps,
    },
    (table) => [
        uniqueIndex("session_token_unique").on(table.token),
        index("session_user_idx").on(table.userId),
        index("session_expires_idx").on(table.expiresAt),
    ],
);

export const account = pgTable(
    "account",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        accountId: text("account_id").notNull(),
        providerId: text("provider_id").notNull(),
        userId: uuid("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        accessToken: text("access_token"),
        refreshToken: text("refresh_token"),
        idToken: text("id_token"),
        accessTokenExpiresAt: timestamp("access_token_expires_at", {
            withTimezone: true,
        }),
        refreshTokenExpiresAt: timestamp("refresh_token_expires_at", {
            withTimezone: true,
        }),
        scope: text("scope"),
        password: text("password"),
        ...timestamps,
    },
    (table) => [
        uniqueIndex("account_provider_unique").on(
            table.providerId,
            table.accountId,
        ),
        index("account_user_idx").on(table.userId),
    ],
);

export const verification = pgTable(
    "verification",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        identifier: text("identifier").notNull(),
        value: text("value").notNull(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        ...timestamps,
    },
    (table) => [
        index("verification_identifier_idx").on(table.identifier),
        index("verification_expires_idx").on(table.expiresAt),
    ],
);

export const homes = pgTable(
    "homes",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        ownerId: uuid("owner_id")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        name: text("name").notNull(),
        type: text("type").notNull(),
        addressLine: text("address_line"),
        city: text("city"),
        postalCode: text("postal_code"),
        country: text("country"),
        constructionYear: integer("construction_year"),
        coverImage: uuid("cover_image"),
        timezone: text("timezone").default("UTC").notNull(),
        archivedAt: timestamp("archived_at", { withTimezone: true }),
        ...timestamps,
    },
    (table) => [
        index("homes_owner_idx").on(table.ownerId),
        index("homes_active_idx").on(table.archivedAt),
    ],
);

export const homeMembers = pgTable(
    "home_members",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        homeId: uuid("home_id")
            .notNull()
            .references(() => homes.id, { onDelete: "cascade" }),
        userId: uuid("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        role: homeRole("role").notNull(),
        invitedBy: uuid("invited_by").references(() => user.id, {
            onDelete: "set null",
        }),
        joinedAt: timestamp("joined_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
        ...timestamps,
    },
    (table) => [
        uniqueIndex("home_member_unique").on(table.homeId, table.userId),
        index("home_members_user_idx").on(table.userId),
        index("home_members_home_role_idx").on(table.homeId, table.role),
    ],
);

export const homeInvitations = pgTable(
    "home_invitations",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        homeId: uuid("home_id")
            .notNull()
            .references(() => homes.id, { onDelete: "cascade" }),
        email: text("email").notNull(),
        role: homeRole("role").notNull(),
        tokenHash: text("token_hash").notNull(),
        invitedBy: uuid("invited_by")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        acceptedAt: timestamp("accepted_at", { withTimezone: true }),
        revokedAt: timestamp("revoked_at", { withTimezone: true }),
        createdAt: timestamp("created_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
    },
    (table) => [
        uniqueIndex("invitation_token_hash_unique").on(table.tokenHash),
        index("invitation_home_email_idx").on(table.homeId, table.email),
        index("invitation_expires_idx").on(table.expiresAt),
    ],
);

export const rooms = pgTable(
    "rooms",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        homeId: uuid("home_id")
            .notNull()
            .references(() => homes.id, { onDelete: "cascade" }),
        name: text("name").notNull(),
        floor: text("floor"),
        icon: text("icon"),
        ...timestamps,
    },
    (table) => [
        uniqueIndex("room_home_name_unique").on(table.homeId, table.name),
        index("rooms_home_idx").on(table.homeId),
    ],
);

export const storedFiles = pgTable(
    "stored_files",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        storageProvider: storageProvider("storage_provider").notNull(),
        storageKey: text("storage_key").notNull(),
        originalName: text("original_name").notNull(),
        mimeType: text("mime_type").notNull(),
        size: integer("size").notNull(),
        checksum: text("checksum").notNull(),
        uploadedBy: uuid("uploaded_by")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        createdAt: timestamp("created_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
        deletedAt: timestamp("deleted_at", { withTimezone: true }),
    },
    (table) => [
        uniqueIndex("stored_file_key_unique").on(
            table.storageProvider,
            table.storageKey,
        ),
        index("stored_files_uploader_idx").on(table.uploadedBy),
    ],
);

export const assets = pgTable(
    "assets",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        homeId: uuid("home_id")
            .notNull()
            .references(() => homes.id, { onDelete: "cascade" }),
        roomId: uuid("room_id").references(() => rooms.id, {
            onDelete: "set null",
        }),
        name: text("name").notNull(),
        category: text("category").notNull(),
        brand: text("brand"),
        model: text("model"),
        serialNumber: text("serial_number"),
        description: text("description"),
        purchaseDate: date("purchase_date"),
        purchasePrice: numeric("purchase_price", { precision: 12, scale: 2 }),
        currency: text("currency").default("EUR"),
        retailer: text("retailer"),
        installationDate: date("installation_date"),
        warrantyStartDate: date("warranty_start_date"),
        warrantyEndDate: date("warranty_end_date"),
        expectedLifetimeYears: integer("expected_lifetime_years"),
        status: assetStatus("status").default("ACTIVE").notNull(),
        imageFileId: uuid("image_file_id").references(() => storedFiles.id, {
            onDelete: "set null",
        }),
        createdBy: uuid("created_by")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        archivedAt: timestamp("archived_at", { withTimezone: true }),
        ...timestamps,
    },
    (table) => [
        index("assets_home_room_idx").on(table.homeId, table.roomId),
        index("assets_home_status_idx").on(table.homeId, table.status),
        index("assets_warranty_expiry_idx").on(table.warrantyEndDate),
    ],
);

export const maintenanceTasks = pgTable(
    "maintenance_tasks",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        homeId: uuid("home_id")
            .notNull()
            .references(() => homes.id, { onDelete: "cascade" }),
        assetId: uuid("asset_id").references(() => assets.id, {
            onDelete: "set null",
        }),
        title: text("title").notNull(),
        description: text("description"),
        frequencyType: frequencyType("frequency_type").notNull(),
        frequencyInterval: integer("frequency_interval").default(1).notNull(),
        nextDueAt: timestamp("next_due_at", { withTimezone: true }).notNull(),
        lastCompletedAt: timestamp("last_completed_at", { withTimezone: true }),
        priority: priority("priority").default("MEDIUM").notNull(),
        estimatedDurationMinutes: integer("estimated_duration_minutes"),
        assignedTo: uuid("assigned_to").references(() => user.id, {
            onDelete: "set null",
        }),
        createdBy: uuid("created_by")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        archivedAt: timestamp("archived_at", { withTimezone: true }),
        ...timestamps,
    },
    (table) => [
        index("maintenance_home_due_idx").on(table.homeId, table.nextDueAt),
        index("maintenance_due_active_idx").on(
            table.nextDueAt,
            table.archivedAt,
        ),
        index("maintenance_assignee_idx").on(table.assignedTo),
    ],
);

export const maintenanceRecords = pgTable(
    "maintenance_records",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        idempotencyKey: text("idempotency_key").notNull(),
        taskId: uuid("task_id").references(() => maintenanceTasks.id, {
            onDelete: "set null",
        }),
        assetId: uuid("asset_id").references(() => assets.id, {
            onDelete: "set null",
        }),
        homeId: uuid("home_id")
            .notNull()
            .references(() => homes.id, { onDelete: "cascade" }),
        completedBy: uuid("completed_by")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        completedAt: timestamp("completed_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
        notes: text("notes"),
        cost: numeric("cost", { precision: 12, scale: 2 }),
        currency: text("currency").default("EUR"),
        serviceProvider: text("service_provider"),
        createdAt: timestamp("created_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
    },
    (table) => [
        uniqueIndex("maintenance_record_idempotency_unique").on(
            table.idempotencyKey,
        ),
        index("maintenance_records_home_idx").on(
            table.homeId,
            table.completedAt,
        ),
        index("maintenance_records_task_idx").on(table.taskId),
    ],
);

export const repairRecords = pgTable(
    "repair_records",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        homeId: uuid("home_id")
            .notNull()
            .references(() => homes.id, { onDelete: "cascade" }),
        assetId: uuid("asset_id")
            .notNull()
            .references(() => assets.id, { onDelete: "cascade" }),
        title: text("title").notNull(),
        description: text("description"),
        issueDate: date("issue_date").notNull(),
        repairDate: date("repair_date"),
        status: repairStatus("status").default("OPEN").notNull(),
        provider: text("provider"),
        cost: numeric("cost", { precision: 12, scale: 2 }),
        currency: text("currency").default("EUR"),
        warrantyClaim: boolean("warranty_claim").default(false).notNull(),
        createdBy: uuid("created_by")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        ...timestamps,
    },
    (table) => [
        index("repairs_home_status_idx").on(table.homeId, table.status),
        index("repairs_asset_idx").on(table.assetId),
    ],
);

export const documents = pgTable(
    "documents",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        homeId: uuid("home_id")
            .notNull()
            .references(() => homes.id, { onDelete: "cascade" }),
        assetId: uuid("asset_id").references(() => assets.id, {
            onDelete: "set null",
        }),
        uploadedBy: uuid("uploaded_by")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        fileId: uuid("file_id")
            .notNull()
            .references(() => storedFiles.id, { onDelete: "restrict" }),
        type: documentType("type").notNull(),
        title: text("title").notNull(),
        description: text("description"),
        documentDate: date("document_date"),
        expiryDate: date("expiry_date"),
        ...timestamps,
    },
    (table) => [
        index("documents_home_type_idx").on(table.homeId, table.type),
        index("documents_asset_idx").on(table.assetId),
        index("documents_expiry_idx").on(table.expiryDate),
    ],
);

export const documentTags = pgTable(
    "document_tags",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        homeId: uuid("home_id")
            .notNull()
            .references(() => homes.id, { onDelete: "cascade" }),
        name: text("name").notNull(),
        normalizedName: text("normalized_name").notNull(),
        createdAt: timestamp("created_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
    },
    (table) => [
        uniqueIndex("document_tags_home_name_unique").on(
            table.homeId,
            table.normalizedName,
        ),
        index("document_tags_home_idx").on(table.homeId),
    ],
);

export const documentTagAssignments = pgTable(
    "document_tag_assignments",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        documentId: uuid("document_id")
            .notNull()
            .references(() => documents.id, { onDelete: "cascade" }),
        tagId: uuid("tag_id")
            .notNull()
            .references(() => documentTags.id, { onDelete: "cascade" }),
        createdAt: timestamp("created_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
    },
    (table) => [
        uniqueIndex("document_tag_assignment_unique").on(
            table.documentId,
            table.tagId,
        ),
        index("document_tag_assignments_document_idx").on(table.documentId),
        index("document_tag_assignments_tag_idx").on(table.tagId),
    ],
);

export const notifications = pgTable(
    "notifications",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        userId: uuid("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        homeId: uuid("home_id").references(() => homes.id, {
            onDelete: "cascade",
        }),
        type: text("type").notNull(),
        title: text("title").notNull(),
        message: text("message").notNull(),
        actionUrl: text("action_url"),
        readAt: timestamp("read_at", { withTimezone: true }),
        dismissedAt: timestamp("dismissed_at", { withTimezone: true }),
        createdAt: timestamp("created_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
    },
    (table) => [
        index("notifications_user_read_idx").on(table.userId, table.readAt),
        index("notifications_user_created_idx").on(
            table.userId,
            table.createdAt,
        ),
    ],
);

export const notificationPreferences = pgTable(
    "notification_preferences",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        userId: uuid("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        emailEnabled: boolean("email_enabled").default(true).notNull(),
        inAppEnabled: boolean("in_app_enabled").default(true).notNull(),
        maintenanceReminderDays: integer("maintenance_reminder_days")
            .default(7)
            .notNull(),
        warrantyReminderDays: integer("warranty_reminder_days")
            .default(30)
            .notNull(),
        documentExpiryReminderDays: integer("document_expiry_reminder_days")
            .default(30)
            .notNull(),
        weeklySummaryEnabled: boolean("weekly_summary_enabled")
            .default(true)
            .notNull(),
        timezone: text("timezone").default("UTC").notNull(),
        ...timestamps,
    },
    (table) => [
        uniqueIndex("notification_preference_user_unique").on(table.userId),
    ],
);

export const reminderDeliveries = pgTable(
    "reminder_deliveries",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        userId: uuid("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        entityType: text("entity_type").notNull(),
        entityId: uuid("entity_id").notNull(),
        reminderType: text("reminder_type").notNull(),
        scheduledFor: timestamp("scheduled_for", {
            withTimezone: true,
        }).notNull(),
        channel: reminderChannel("channel").notNull(),
        status: deliveryStatus("status").default("PENDING").notNull(),
        deliveredAt: timestamp("delivered_at", { withTimezone: true }),
        error: text("error"),
        idempotencyKey: text("idempotency_key").notNull(),
        createdAt: timestamp("created_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
    },
    (table) => [
        uniqueIndex("reminder_idempotency_unique").on(table.idempotencyKey),
        index("reminder_pending_idx").on(table.status, table.scheduledFor),
    ],
);

export const auditLogs = pgTable(
    "audit_logs",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        actorId: uuid("actor_id").references(() => user.id, {
            onDelete: "set null",
        }),
        homeId: uuid("home_id").references(() => homes.id, {
            onDelete: "set null",
        }),
        action: text("action").notNull(),
        targetType: text("target_type").notNull(),
        targetId: uuid("target_id"),
        requestId: text("request_id"),
        ipHash: text("ip_hash"),
        metadata:
            jsonb("metadata").$type<
                Record<string, string | number | boolean | null>
            >(),
        createdAt: timestamp("created_at", { withTimezone: true })
            .defaultNow()
            .notNull(),
    },
    (table) => [
        index("audit_home_created_idx").on(table.homeId, table.createdAt),
        index("audit_actor_created_idx").on(table.actorId, table.createdAt),
    ],
);

export const rateLimitEntries = pgTable(
    "rate_limit_entries",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        keyHash: text("key_hash").notNull(),
        action: text("action").notNull(),
        count: integer("count").default(1).notNull(),
        windowStartedAt: timestamp("window_started_at", {
            withTimezone: true,
        }).notNull(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    },
    (table) => [
        uniqueIndex("rate_limit_key_action_unique").on(
            table.keyHash,
            table.action,
        ),
        index("rate_limit_expiry_idx").on(table.expiresAt),
    ],
);
